# Generated by Django 5.0 on 2023-12-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='email',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='records',
            name='phone_no',
            field=models.CharField(max_length=10),
        ),
    ]
